export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  MATCHES: '/matches',
  MATCH_DETAIL: '/matches/:id',
  TEAM: '/team',
  PROFILE: '/profile',
  DASHBOARD: '/dashboard',
  ADMIN_CLUB: '/admin/club',
  ADMIN_USERS: '/admin/users',
  COACH_COMMAND_CENTER: '/coach',
  COACH_ANALYTICS: '/coach/analytics',
  PLAYER_SCHEDULE: '/me/schedule',
  PARENT_OVERVIEW: '/parent/overview',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
} as const;
